import type {
  Department,
  Task,
  Document,
  FeedItem,
  User,
  Production,
} from "./types";

export const production: Production = {
  id: "prod-1",
  title: "La Última Escena",
  description:
    "A psychological drama set in a crumbling theater, where a reclusive director stages one final play that blurs the line between performance and reality.",
  stage: "pre-production",
  startDate: "2026-04-01",
  endDate: "2026-08-30",
};

export const departments: Department[] = [
  {
    id: "photography",
    name: "Photography",
    icon: "Camera",
    color: "#e67e22",
    roles: ["photography"],
  },
  {
    id: "art",
    name: "Art Direction",
    icon: "Palette",
    color: "#9b59b6",
    roles: ["art"],
  },
  {
    id: "cinematography",
    name: "Cinematography",
    icon: "Film",
    color: "#2980b9",
    roles: ["cinematography"],
  },
  {
    id: "sound",
    name: "Sound",
    icon: "Music",
    color: "#27ae60",
    roles: ["sound"],
  },
  {
    id: "production",
    name: "Production",
    icon: "Clapperboard",
    color: "#e74c3c",
    roles: ["production"],
  },
  {
    id: "costume",
    name: "Costume Design",
    icon: "Shirt",
    color: "#f39c12",
    roles: ["costume"],
  },
  {
    id: "makeup",
    name: "Makeup & Hair",
    icon: "Sparkles",
    color: "#e91e63",
    roles: ["makeup"],
  },
  {
    id: "editing",
    name: "Editing",
    icon: "Scissors",
    color: "#607d8b",
    roles: ["editing"],
  },
];

export const users: User[] = [
  {
    id: "user-1",
    name: "Sofía Méndez",
    avatar: "SM",
    roles: ["assistant-director"],
    departmentIds: [
      "photography",
      "art",
      "cinematography",
      "sound",
      "production",
      "costume",
      "makeup",
      "editing",
    ],
  },
  {
    id: "user-2",
    name: "Carlos Rivera",
    avatar: "CR",
    roles: ["director"],
    departmentIds: [
      "photography",
      "art",
      "cinematography",
      "sound",
      "production",
      "costume",
      "makeup",
      "editing",
    ],
  },
  {
    id: "user-3",
    name: "Lucía Torres",
    avatar: "LT",
    roles: ["photography"],
    departmentIds: ["photography"],
  },
  {
    id: "user-4",
    name: "Mateo Herrera",
    avatar: "MH",
    roles: ["art"],
    departmentIds: ["art"],
  },
  {
    id: "user-5",
    name: "Valentina Cruz",
    avatar: "VC",
    roles: ["cinematography"],
    departmentIds: ["cinematography"],
  },
  {
    id: "user-6",
    name: "Diego Paredes",
    avatar: "DP",
    roles: ["sound"],
    departmentIds: ["sound"],
  },
  {
    id: "user-7",
    name: "Isabela Rojas",
    avatar: "IR",
    roles: ["production"],
    departmentIds: ["production"],
  },
  {
    id: "user-8",
    name: "Andrés Guzmán",
    avatar: "AG",
    roles: ["costume"],
    departmentIds: ["costume"],
  },
  {
    id: "user-9",
    name: "Camila Díaz",
    avatar: "CD",
    roles: ["makeup"],
    departmentIds: ["makeup"],
  },
  {
    id: "user-10",
    name: "Nicolás Vargas",
    avatar: "NV",
    roles: ["editing"],
    departmentIds: ["editing"],
  },
];

export const tasks: Task[] = [
  {
    id: "task-1",
    title: "Light map for theater interior — Scene 12",
    description:
      "Create a detailed light map for the interior of the crumbling theater. The director wants warm, decaying golden tones with sharp shadows from stage lights.",
    departmentId: "photography",
    assignedTo: "user-3",
    status: "in-progress",
    dueDate: "2026-04-15",
    scene: "Scene 12",
    comments: [
      {
        id: "c1",
        authorId: "user-2",
        text: "I want the shadows to feel almost like prison bars — structured but oppressive. Think Caravaggio meets Kubrick.",
        createdAt: "2026-04-05T10:30:00Z",
      },
      {
        id: "c2",
        authorId: "user-3",
        text: "Got it. I'll prepare two versions: one with hard overhead spots and another with diffused side fill. Will have the map ready by Thursday.",
        createdAt: "2026-04-05T14:15:00Z",
      },
    ],
    createdAt: "2026-04-02T09:00:00Z",
  },
  {
    id: "task-2",
    title: "Set design sketches for main stage",
    description:
      "Draw initial sketches for the main stage of the theater. The set should feel grand but decayed — faded velvet, cracked plaster, dust in the air.",
    departmentId: "art",
    assignedTo: "user-4",
    status: "pending",
    dueDate: "2026-04-20",
    scene: "Scene 1-5",
    comments: [],
    createdAt: "2026-04-03T08:00:00Z",
  },
  {
    id: "task-3",
    title: "Camera movement plan — Opening sequence",
    description:
      "Plan the dolly and crane movements for the 3-minute opening. Single take through the empty theater, discovering characters one by one.",
    departmentId: "cinematography",
    assignedTo: "user-5",
    status: "pending",
    dueDate: "2026-04-18",
    scene: "Scene 1",
    comments: [
      {
        id: "c3",
        authorId: "user-2",
        text: "This has to feel like the camera is a ghost floating through the theater. Smooth, dreamlike, no visible cuts.",
        createdAt: "2026-04-04T11:00:00Z",
      },
    ],
    createdAt: "2026-04-03T10:00:00Z",
  },
  {
    id: "task-4",
    title: "Ambient sound palette research",
    description:
      "Gather reference sounds: creaking wood, distant footsteps, echoing voices, wind through broken windows. Build an ambient soundscape palette.",
    departmentId: "sound",
    assignedTo: "user-6",
    status: "done",
    dueDate: "2026-04-10",
    comments: [],
    createdAt: "2026-04-02T12:00:00Z",
  },
  {
    id: "task-5",
    title: "Budget breakdown — Locations & permits",
    description:
      "Compile costs for all potential shooting locations and necessary permits. Include at least 3 theater options with availability windows.",
    departmentId: "production",
    assignedTo: "user-7",
    status: "in-progress",
    dueDate: "2026-04-12",
    comments: [],
    createdAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "task-6",
    title: "Protagonist costume mood board",
    description:
      "Create a mood board for Elena's wardrobe arc: starts sharp and composed (tailored blacks), gradually unravels into layers and textures.",
    departmentId: "costume",
    assignedTo: "user-8",
    status: "done",
    dueDate: "2026-04-08",
    comments: [
      {
        id: "c4",
        authorId: "user-2",
        text: "Perfect. The arc from control to chaos should be visible in every thread. This is exactly the progression I envisioned.",
        createdAt: "2026-04-08T16:00:00Z",
      },
    ],
    createdAt: "2026-04-02T14:00:00Z",
  },
  {
    id: "task-7",
    title: "Aging makeup tests for lead actor",
    description:
      "Schedule and prep aging prosthetics tests. The character ages visually across the film through stress and exhaustion, not literal years.",
    departmentId: "makeup",
    assignedTo: "user-9",
    status: "pending",
    dueDate: "2026-04-22",
    comments: [],
    createdAt: "2026-04-04T09:00:00Z",
  },
  {
    id: "task-8",
    title: "Assembly edit — Reference cut from rehearsal footage",
    description:
      "Put together a rough reference cut from rehearsal footage to help plan pacing and transitions for the final edit.",
    departmentId: "editing",
    assignedTo: "user-10",
    status: "pending",
    dueDate: "2026-04-25",
    comments: [],
    createdAt: "2026-04-05T08:00:00Z",
  },
  {
    id: "task-9",
    title: "Location scouting photos — Abandoned theaters",
    description:
      "Visit 3 shortlisted theaters and capture high-res reference photos of interiors, backstage areas, and exterior facades.",
    departmentId: "photography",
    assignedTo: "user-3",
    status: "done",
    dueDate: "2026-04-07",
    comments: [],
    createdAt: "2026-04-01T08:00:00Z",
  },
  {
    id: "task-10",
    title: "Props list — Act I scenes",
    description:
      "Compile a full props list for Act I scenes. Include vintage typewriter, dusty scripts, broken spotlight, and wilted flowers.",
    departmentId: "art",
    assignedTo: "user-4",
    status: "in-progress",
    dueDate: "2026-04-16",
    comments: [],
    createdAt: "2026-04-04T11:00:00Z",
  },
  {
    id: "task-11",
    title: "Lens selection test — Anamorphic vs Spherical",
    description:
      "Run comparison tests between anamorphic and spherical lenses for key scenes. Director prefers an organic, slightly dreamy feel.",
    departmentId: "cinematography",
    assignedTo: "user-5",
    status: "in-progress",
    dueDate: "2026-04-14",
    comments: [
      {
        id: "c5",
        authorId: "user-5",
        text: "Initial tests suggest anamorphic primes will give us the bokeh and flare character we want. Setting up more comparisons.",
        createdAt: "2026-04-06T15:00:00Z",
      },
    ],
    createdAt: "2026-04-03T12:00:00Z",
  },
  {
    id: "task-12",
    title: "Shooting schedule — First two weeks",
    description:
      "Draft the first two weeks of the shooting schedule, coordinating location availability with actor schedules and department readiness.",
    departmentId: "production",
    assignedTo: "user-7",
    status: "pending",
    dueDate: "2026-04-28",
    comments: [],
    createdAt: "2026-04-05T10:00:00Z",
  },
];

export const documents: Document[] = [
  {
    id: "doc-1",
    title: "Director's Vision Statement",
    type: "document",
    url: "#",
    departmentId: "production",
    uploadedBy: "user-2",
    createdAt: "2026-04-01T08:00:00Z",
  },
  {
    id: "doc-2",
    title: "Theater Interior — Mood Board",
    type: "moodboard",
    url: "#",
    departmentId: "art",
    uploadedBy: "user-4",
    createdAt: "2026-04-03T10:00:00Z",
  },
  {
    id: "doc-3",
    title: "Light Reference — Caravaggio Collection",
    type: "image",
    url: "#",
    departmentId: "photography",
    uploadedBy: "user-3",
    createdAt: "2026-04-04T09:00:00Z",
  },
  {
    id: "doc-4",
    title: "Budget Spreadsheet v2",
    type: "spreadsheet",
    url: "#",
    departmentId: "production",
    uploadedBy: "user-7",
    createdAt: "2026-04-05T14:00:00Z",
  },
  {
    id: "doc-5",
    title: "Sound Reference — Tarkovsky Ambience",
    type: "link",
    url: "#",
    departmentId: "sound",
    uploadedBy: "user-6",
    createdAt: "2026-04-02T16:00:00Z",
  },
  {
    id: "doc-6",
    title: "Elena Costume Progression — Mood Board",
    type: "moodboard",
    url: "#",
    departmentId: "costume",
    uploadedBy: "user-8",
    createdAt: "2026-04-06T10:00:00Z",
  },
  {
    id: "doc-7",
    title: "Lens Test Results — Photo Gallery",
    type: "image",
    url: "#",
    departmentId: "cinematography",
    uploadedBy: "user-5",
    createdAt: "2026-04-06T15:30:00Z",
  },
  {
    id: "doc-8",
    title: "Shooting Schedule Draft",
    type: "spreadsheet",
    url: "#",
    departmentId: "production",
    uploadedBy: "user-7",
    createdAt: "2026-04-07T10:00:00Z",
  },
];

export const feedItems: FeedItem[] = [
  {
    id: "feed-1",
    authorId: "user-6",
    type: "task-completed",
    content: "completed 'Ambient sound palette research'",
    departmentId: "sound",
    taskId: "task-4",
    createdAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "feed-2",
    authorId: "user-8",
    type: "task-completed",
    content: "completed 'Protagonist costume mood board'",
    departmentId: "costume",
    taskId: "task-6",
    createdAt: "2026-04-08T15:00:00Z",
  },
  {
    id: "feed-3",
    authorId: "user-2",
    type: "comment",
    content:
      "left a comment on 'Light map for theater interior': \"Think Caravaggio meets Kubrick.\"",
    departmentId: "photography",
    taskId: "task-1",
    createdAt: "2026-04-05T10:30:00Z",
  },
  {
    id: "feed-4",
    authorId: "user-4",
    type: "document-added",
    content: "uploaded 'Theater Interior — Mood Board' to Art Direction",
    departmentId: "art",
    createdAt: "2026-04-03T10:00:00Z",
  },
  {
    id: "feed-5",
    authorId: "user-3",
    type: "task-completed",
    content: "completed 'Location scouting photos — Abandoned theaters'",
    departmentId: "photography",
    taskId: "task-9",
    createdAt: "2026-04-07T17:00:00Z",
  },
  {
    id: "feed-6",
    authorId: "user-2",
    type: "announcement",
    content:
      "Welcome to the production bible for 'La Última Escena'. Every department has its own space — keep it updated and check often. Let's make something extraordinary.",
    createdAt: "2026-04-01T08:00:00Z",
  },
  {
    id: "feed-7",
    authorId: "user-5",
    type: "document-added",
    content: "uploaded 'Lens Test Results' to Cinematography",
    departmentId: "cinematography",
    createdAt: "2026-04-06T15:30:00Z",
  },
  {
    id: "feed-8",
    authorId: "user-7",
    type: "document-added",
    content: "uploaded 'Budget Spreadsheet v2' to Production",
    departmentId: "production",
    createdAt: "2026-04-05T14:00:00Z",
  },
];
